### ISSUE TITLE
EEBase PractitionerRole

### ISSUE THREAD

**Issue by KristiinaKuldkepp** [HL7EE/ig-ee-base#10]
<html>
<body>

Element | Kommentaar
-- | --
code | R5 slicitud: code:role ja code:tor ? töötamise rgister? tehtud selline https://fhir.ee/ValueSet/ee-practitioner-role - kas siin on piisavalt elemente? Bindingud erinevad.
speciality | slicitud; speciality ja eriala (Medre (required) - experimental value set (vaja täiendust!)
telecom | R5-s contact
characteristic | uus! ainult R5s. Binding ServiceMode value-setiga. Tundub OK
availableTime ja notAvailabble | R5s nende asemel availability

</body>
</html>

**Comment by igorboss** [comment]
- slicing code ja specialty elementidel on vajalik algusest, kuna nad hakkavad sisaldama andmed erinevatest koodisüsteemidest. Igal slice binding oma value setile. Slice-ide struktuur kooskõlastatud TAI-ga ja illustreeritud mitme näidetega.

**Comment by KristiinaKuldkepp** [comment]
ValueSet:[ Medre Specialty (Experimental) ](ValueSet: Medre Specialty (Experimental))on poolik ja alles kokkuleppimisel töörühmas. Ettepanek on mitte panna poolikut asja EEBase. Kuidas lahendada @ragneoitspuu @igorboss ?

**Comment by rlindstrm** [comment]
@ragneoitspuu, testisin fragmendi toimimist.

Praegu on nii, et kui panna MEDRE erialakoodiks kood, mida IGs toodud koodisüsteemi fragmendis ei ole, siis sushi viga ei anna ja build töötab, aga QA-s logitakse siiski error: 
None of the codings provided are in the value set 'Medre Specialty' (https://fhir.ee/ValueSet/ee-medre-specialty|0.9.0), and a coding from this value set is required) (codes = https://fhir.ee/CodeSystem/ee-medre-specialty#E270)

![image](https://github.com/HL7EE/ig-ee-base/assets/112903984/c227710a-d909-4f9e-a1cb-e45604d62095)

**Comment by ragneoitspuu** [comment]
@igorboss kas panna EEBase'is Medre Speciality loendi binding example?

**Comment by igorboss** [comment]
Jah, selleks et vigu poleks tuleb lisada
