### ISSUE TITLE
EEBase RelatedPerson

### ISSUE THREAD

**Issue by KristiinaKuldkepp** [HL7EE/ig-ee-base#11]
<html>
<body>

Element | Kommentaar
-- | --
identifier | R5 mustsupport system ja value; (R4 est-id mustsupport). Person Identity System
relationship | R5 slicitud: class ja person. Ei saa aru mis vahe neil on?
communication (language) | R5 required (R4 preferred) binding AllLanguages valuesetiga

</body>
</html>

**Comment by KristiinaKuldkepp** [comment]
Ta küsimusele vastas ise. Järgnes number: õngevise! (Jüri Üdi) - class on HL7 loendiga, person on SNOMED

**Comment by igorboss** [comment]
- Jah - class on HL7 loendiga, person on SNOMED. Kui me ikkagi loobume SNOMED-ist seotud isiku märgistamisel siis saame loobuda ka slice-ingust.
- AllLanguangues siin ja mujal tuli R5-ga
- Identifier läbivalt asendatud NamingSystemist (mis ei töötanud) value seti peale.
