### ISSUE TITLE
IG kujundus

### ISSUE THREAD

**Issue by ragneoitspuu** [HL7EE/ig-ee-base#13]
1. Kas meil oleks võimalik IG headeris muuta lilla värk siniseks nii, nagu on [Soomel](http://hl7.fi/fhir/finnish-base-profiles/index.html)?
![image](https://github.com/HL7EE/ig-ee-base/assets/122268687/143fec4c-8cfc-4a76-b714-8e606596d429)

2. Profiilides on sinine riba, mille alt ei näe tulba pealkirju, kas saaks selle ära võtta?
![image](https://github.com/HL7EE/ig-ee-base/assets/122268687/63c44c65-386b-4dd9-a011-bfd5044a573b)

**Comment by igorboss** [comment]
1. Jah, juhendon siin https://build.fhir.org/ig/FHIR/ig-guidance/index.html. Localtemplate kaust mul juba loodud saab hakkata toimetama seal.
2. Võtsin stiilid Simplifierist, aga nad väga hästi ei sobi. Disainer võiks ülekäia projekti üle.

**Comment by ragneoitspuu** [comment]
Meil tegeles Simplifieris IG kujundusega Grete, kes on hetkel puhkusel, seega me Kristiinaga seda muuta ei oska kahjuks. Kas saaksid ise muuta?

**Comment by igorboss** [comment]
Ei, kahjuks visuaal ei ole minu valdkond
