### ISSUE TITLE
EEBase Example

### ISSUE THREAD

**Issue by KristiinaKuldkepp** [HL7EE/ig-ee-base#14]
![image](https://github.com/HL7EE/ig-ee-base/assets/133873675/bae5413f-f46c-4b23-bf9c-d3f18cbe2e25)
<[system](http://hl7.org/fhir/R5/datatypes.html#Identifier#Identifier.system) [value](http://hl7.org/fhir/R5/datatypes.html#uri)="https://fhir.ee/sid/pid/est/ni"/>
    <[value](http://hl7.org/fhir/R5/datatypes.html#Identifier#Identifier.value) [value](http://hl7.org/fhir/R5/datatypes.html#string)="YYYYYY6"/>

Peaks olema usutavam Eesti isikukood

**Comment by igorboss** [comment]
Palun muuda endale sobilikuks
