### ISSUE TITLE
EEBase EpisodeOfCare

### ISSUE THREAD

**Issue by ragneoitspuu** [HL7EE/ig-ee-base#3]
<html>
<body>

Element | Kommentaar
-- | --
reason > value | R5 puudub viide EEBase Observation ja EEBase HealthcareService
type | [R4 elemendi kirjelduses](https://simplifier.net/guide/ee-fhir-base/Home/Profiles-and-Extensions/Profile-EEBaseEpisodeOfCare?version=current#type) on kirjas loendina EEBaseEpisodeOfCareType.  [Wikis](https://wiki.sm.ee/display/UPFHIR/EEBaseEpisodeOfCare) on kirjas, et teeme siia loendi, aga hetkel me selle loendiga ei tegele.

**Comment by igorboss** [comment]
- reason > value - fixed
- type - ei eelda millegi tegemist
