### ISSUE TITLE
EEBase Location

### ISSUE THREAD

**Issue by ragneoitspuu** [HL7EE/ig-ee-base#5]
<html>
<body>

Element | Kommentaar
-- | --
address | R5 mustSupport, R4 ei ole
form | R5 mustSupport, R4 ei ole
managingOrganization | R5 mustSupport, R4 ei ole

**Comment by igorboss** [comment]
Mulle tundub, et Location ilma seoseta üksusega ja tüübita ei oma mõtet.
Aadress on ka oluline, et patsient leiaks õige koha, aga selle tähtsus on väiksem, kui 2 eelmist.
Paneks hääletusele?

**Comment by ragneoitspuu** [comment]
MustSupportid jäävad hetkel sisse.
