### ISSUE TITLE
EEBase Organization

### ISSUE THREAD

**Issue by ragneoitspuu** [HL7EE/ig-ee-base#7]
<html>
<body>

Element | Kommentaar
-- | --
identifier > assigner | R5 puudub viide EEbase Organization
type| oleme loomas asutuse tüübi loendit tervise valdkonna loendite töörühmas
contact > referenceRange | R5 mustSupport, R4 mitte
address | kas õige oleks EEBase Address (ehk siis tühikuga, mitte EEBaseAddress)?

</body>
</html>

**Comment by igorboss** [comment]
- identifier > assigner - kas sellel on praktiline vajadus?  1) Suure tõenäosusega assigneri mitte kunagi ei kasutata Organization identifikaatoris 2) ja kui kasutatakse siis viitena, ehk EEbase eripärasid ei kasutata
- type - ok. Hetkel siis 100% FHIR loend
- contact MS - fixed
- tundub, et andmetüüpide puhul kuvatakse ComputableName ja mitte Title. Muidu Title on korrektne
