### ISSUE TITLE
EEBase Patient

### ISSUE THREAD

**Issue by KristiinaKuldkepp** [HL7EE/ig-ee-base#8]
<html>
<body>

Element | Kommentaar
-- | --
identifier | R4 slice asemel R5-s Person Identity System
name | R5-s slicitud kaheks - official ja nickname. Nickname on anonüümse patsiendi jaoks tehtud. vist ok?
telecom | alla tekkinud 4 elementi: system, value, use, period; required binding ContactPointSystemiga. Tundub mõistlik.
birthDate | R5-s slicitud - lisaks birthTime-le lisatud age ja accuracyIndicator (uus extension)
deceased | lisatud extension accuracyIndicator (see tuleks elemendina rohkem lahti kirjutada)
communication | see on kadunud R5-st (kas sellepärast et pole mustsupport?) - uurime
  | Miks on EEBaseAdministrativeGender? Kas HL7 loendist ei piisa? Kas tõlgete pärast uus valueset?kui tuleb uus identifikaatorite süsteem siis Intro jutt R4 IG-st enam ei päde ja sissejuhatav lause on ok. Või siisiki eemaldada "animal"?

</body>
</html>

**Comment by igorboss** [comment]
- Identifier läbivalt asendatud NamingSystemist (mis ei töötanud) value seti peale.
- communication - on näha snapshotis. Kuna me midagi ei muuda siis diffis teda pole.
- dateAccuracy - praegune kirjeldus on [koodisüsteemi](https://build.fhir.org/ig/HL7EE/ig-ee-base/branches/master/CodeSystem-ee-date-accuracy-indicator.html) juures. Kas lisad extensioni lauset "See code system definition for the details"?
- nime osas ilmselt peaksime hääletama? Mulle tundub, et me võiksime nõuda et eesnimi ja nimi on kohustuslikud ametliku nime puhul? Teiste võimaluste jaoks päris palju "use"  väärtusi.

**Comment by KristiinaKuldkepp** [comment]
- koodisüsteemi juures dateAccuracy kirjeldus on piisav
- family ja given on 1..1 official-i puhul. See on ok minu arust.
