### ISSUE TITLE
EEBase Practitioner

### ISSUE THREAD

**Issue by KristiinaKuldkepp** [HL7EE/ig-ee-base#9]
<html>
<body>

Element | Kommentaar
-- | --
identifier | Tehtud slicede (namingsystemid Medre TAM jne) asemel Valueset: Practitioner Identity System (Experimental); jaguneb kaheks system ja element. Tundub loogiline
qualification | R5: slicitud, degree on mustsupport seotud ValueSet: Qualificationiga - see on poolik!; seotud loendiga ValueSet: hl7VS-degreeLicenseCertificate ; Issuer on Organization → peaks olema EEBase Organisation
  | Siin on olemas Purpose ja Use-cases peatükid intros.Kas teeme kõik profiilid sarnaselt?

</body>
</html>

**Comment by KristiinaKuldkepp** [comment]
qualification:degree: Issuer on Organization → peaks olema **EEBase Organisation**

**Comment by igorboss** [comment]
> qualification:degree: Issuer on Organization → peaks olema EEBase Organisation

Nii ongi "qualification:All Slices" -> Reference EEBase Organization

**Comment by igorboss** [comment]
> jätame selle pooliku Value Seti ära https://fhir.ee/ValueSet/ee-degree-license-certificate
